### ISSUE TITLE
Cannot train example

### ISSUE THREAD

**Issue by urialon** [eth-sri/debin#2]
Hi again,
I'm trying to train the model on the example/lcrack provided example. I'm running:

```
python3 py/train_variable.py \
          --bin_list examples/bin_list.txt \
          --bin_dir examples/stripped/ \
          --debug_dir examples/debug/ \
          --out_model new_models/variable/x86/ \
          --reg_num_f 100 \
          --off_num_f 100
```

And I am getting the following error:
```
Traceback (most recent call last):
  File "py/train_variable.py", line 142, in <module>
    main()
  File "py/train_variable.py", line 137, in main
    train(reg_x, reg_y, args.reg_num_p, args.reg_num_n, args.reg_num_f, args.n_estimators, args.workers, 'reg', args.out_model)
  File "py/train_variable.py", line 97, in train
    X = dict_vec.transform(X)
  File "/home/urialon/.local/lib/python3.6/site-packages/sklearn/feature_extraction/dict_vectorizer.py", line 292, in transform
    return self._transform(X, fitting=False)
  File "/home/urialon/.local/lib/python3.6/site-packages/sklearn/feature_extraction/dict_vectorizer.py", line 184, in _transform
    raise ValueError("Sample sequence X is empty.")
ValueError: Sample sequence X is empty.
```

Thanks!

**Comment by urialon** [comment]
It was my fault, missed some of the dependencies.

**Comment by kotaket** [comment]
I realize this is from years ago, but would you happen to remember what dependencies were missing/where you found them?

**Comment by urialon** [comment]
No, sorry :-)
