### ISSUE TITLE
There are some problems with the file directory

### ISSUE THREAD

**Issue by hhqd** [eth-sri/debin#20]
hello
when i run the command:
"$ python3 py/train_crf.py \
          --bin_list examples/bin_list.txt \
          --bin_dir examples/stripped/ \
          --debug_dir examples/debug/ \
          --out_model new_models/crf/x86/model \
          --n2p_train Nice2Predict/bazel-bin/n2p/training/train_json \
          --log_dir new_models/crf \
          --valid_labels c_valid_labels"

it returned some errors:
"DEBUG Binary __init__ bap command bap examples/stripped/mbe --pass=loc --symbolizer=objdump
Traceback (most recent call last):
  File "py/bin_to_graph.py", line 86, in <module>
    main()
  File "py/bin_to_graph.py", line 71, in main
    b = Binary(config, elffile, debug_elffile)
  File "/debin/py/binary.py", line 92, in __init__
    bap_json = json.loads(bap_result)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
cat: new_models/crf/mbe: No such file or directory
/bin/sh: 1: Nice2Predict/bazel-bin/n2p/training/train_json: not found
"
Is there any problem with the file directory?
thanks

**Comment by LostBenjamin** [comment]
Hi,

Can you provide a formatted version of the error? It is hard for me to find the cause with the unformatted version.

Best,
Jingxuan

**Comment by LostBenjamin** [comment]
Closing due to inactivity.
